apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    name: deployment
    app: my-app
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30002
  type: NodePort
