apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-app
spec:
   replicas: 2
   selector:
      matchLabels:
         name: deployment
         app: my-app
   template: 
      metadata: 
         labels: 
            name: deployment
            app: my-app
      spec: 
         containers:
            - name: my-app
              image: mitrasonal/my-app:v1
              ports:
                - containerPort: 3005
              env: 
                - name: MONGO_URL
                  value: "mongodb://admin:password@mongo:27017/mydatabase?authSource=admin"
                - name: REDIS_URL
                  value: "redis://redis:6379"
