apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-express
      app: my-app
  template:
    metadata:
      labels:
        name: mongo-express
        app: my-app  
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "password"
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongo"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "sonal"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "sonal"

