apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    name: mongo-express
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30000  # Specify the NodePort here, e.g., 30000
  type: NodePort
