---
apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  labels:
    name: nod_app_sevice
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 3005
    targetPort: 3005
    nodePort: 30004
  selector:
    name: deployment
    app: appe_nod
